import { NativeStackScreenProps } from '@react-navigation/native-stack';
import * as Linking from 'expo-linking';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { RootStackParamList } from '../navigation/types';

type Props = NativeStackScreenProps<RootStackParamList, 'Safety'>;

const PRIVACY_URL = 'https://safepsy.com/security-and-privacy-policy';

export function SafetyDisclaimerScreen({ navigation }: Props) {
  return (
    <ScrollView contentContainerStyle={styles.scroll}>
      <Text style={styles.title}>Important — read before use</Text>

      <Text style={styles.section}>Not a medical device</Text>
      <Text style={styles.p}>
        SafePsy and Dr.Safe are not medical devices, not FDA-cleared software, and not a substitute for
        diagnosis, treatment, or professional mental health care.
      </Text>

      <Text style={styles.section}>Not for crisis or emergencies</Text>
      <Text style={styles.p}>
        Do not use this app in a crisis. If you or someone else may be in danger, call emergency services
        immediately.
      </Text>
      <View style={styles.crisisBox}>
        <Text style={styles.crisisLine}>
          <Text style={styles.crisisStrong}>United States — 988:</Text> Suicide & Crisis Lifeline (call or
          text).
        </Text>
        <Text style={styles.crisisLine}>
          <Text style={styles.crisisStrong}>United States — 911:</Text> medical or life-threatening
          emergencies.
        </Text>
        <Text style={styles.crisisLine}>
          <Text style={styles.crisisStrong}>European Union — 112:</Text> emergency number (EU-wide).
        </Text>
      </View>

      <Text style={styles.section}>AI-generated responses</Text>
      <Text style={styles.p}>
        Dr.Safe replies are generated by artificial intelligence. They may be inaccurate, incomplete, or
        inappropriate for your situation. Always verify important information with a qualified professional.
      </Text>

      <Text style={styles.section}>Wallet & data (summary)</Text>
      <Text style={styles.p}>
        Your wallet address is used to authenticate you and to associate usage with your account. Chat
        content you choose to save is encrypted on your device before upload; the server stores ciphertext,
        not plain text. AI providers process prompts you send according to our privacy policy.
      </Text>
      <Text style={styles.p}>
        The full privacy policy (including wallet usage, encrypted storage, and AI processing) is on the
        web:
      </Text>
      <Pressable onPress={() => void Linking.openURL(PRIVACY_URL)}>
        <Text style={styles.link}>{PRIVACY_URL}</Text>
      </Pressable>

      <Text style={styles.section}>Beta software</Text>
      <Text style={styles.p}>
        Continue only if you understand this is a beta software experience and not clinical treatment.
      </Text>

      <Pressable style={styles.primaryBtn} onPress={() => navigation.navigate('Chat')}>
        <Text style={styles.primaryBtnText}>I understand — open chat</Text>
      </Pressable>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  scroll: { padding: 20, paddingBottom: 48 },
  title: { fontSize: 22, fontWeight: '700', marginBottom: 16 },
  section: { fontSize: 17, fontWeight: '700', marginTop: 18, marginBottom: 8, color: '#111' },
  p: { fontSize: 16, lineHeight: 24, marginBottom: 12, color: '#222' },
  crisisBox: {
    backgroundColor: '#f4f8fb',
    borderRadius: 10,
    padding: 14,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#cde',
  },
  crisisLine: { fontSize: 15, lineHeight: 22, marginBottom: 8, color: '#222' },
  crisisStrong: { fontWeight: '700' },
  link: {
    marginTop: 4,
    marginBottom: 8,
    fontSize: 15,
    fontWeight: '600',
    color: '#1a5f7a',
  },
  primaryBtn: {
    marginTop: 24,
    backgroundColor: '#1a5f7a',
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
  },
  primaryBtnText: { color: '#fff', fontSize: 16, fontWeight: '600' },
});
